// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"erpaa/backend/internal/handler"
	"erpaa/backend/internal/repository"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedApp(db *gorm.DB) *App {
	userPatern := repository.NewUserImplemen(db)
	handlerUser := handler.NewHandlerUser(userPatern)
	app := NewApp(handlerUser)
	return app
}

// wire.go:

type App struct {
	UserHandler *handler.HandlerUser
}

func NewApp(
	hu *handler.HandlerUser,
) *App {
	return &App{
		UserHandler: hu,
	}
}
